DROP TABLE `CUSTOMER`;
CREATE TABLE `CUSTOMER` (
  `CUSTOMERID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMERNAME` varchar(200) DEFAULT NULL,
  `MEMBERSINCE` datetime DEFAULT NULL,
  `BALANCE` float DEFAULT NULL,
  `AddressId` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`CUSTOMERID`)
);

DROP TABLE `ADDRESS`;
CREATE TABLE `ADDRESS` (
  `ADDRESSID` bigint(20) NOT NULL AUTO_INCREMENT,
  `HOUSENUMBER` int(11) DEFAULT NULL,
  `STREET` varchar(200) DEFAULT NULL,
  `CITY` varchar(200) DEFAULT NULL,
  `STATE` varchar(200) DEFAULT NULL,
  `COUNTRY` varchar(200) DEFAULT NULL,
  `OWNERTYPEID` int(11) DEFAULT NULL,
  `ADDRESSTYPEID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ADDRESSID`)
);

DROP TABLE `CONTACT`;
CREATE  TABLE `CONTACT` (
  `CONTACTID` BIGINT NOT NULL AUTO_INCREMENT ,
  `PHONENUMBER` VARCHAR(200) NULL ,
  `PHONETYPE` VARCHAR(200) NULL ,
  `CONTACTTYPE` VARCHAR(200) NULL ,
  `EMAILID` VARCHAR(200) NULL ,
  `CUSTOMERID` int(11) NOT NULL,
  PRIMARY KEY (`CONTACTID`) );

DROP TABLE `CREDITCARD`;
CREATE TABLE `CREDITCARD` (
  `CREDITCARDID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CARDNUMBER` varchar(200) DEFAULT NULL,
  `SECURITYCODE` varchar(200) DEFAULT NULL,
  `EXPDATE` datetime DEFAULT NULL,
  `CARDTYPE` varchar(200) DEFAULT NULL,
  `CUSTOMERID` int(11) NOT NULL,
  PRIMARY KEY (`CREDITCARDID`)
);

DROP TABLE `OWNERTYPES`;
CREATE TABLE `OWNERTYPES` (
  `OWNERTYPEID` INT NOT NULL ,
  `OWNERTYPENAME` VARCHAR(45) NULL ,
  PRIMARY KEY (`OWNERTYPEID`) );

DROP TABLE `ADDRESSTYPES`;
CREATE  TABLE `ADDRESSTYPES` (
  `ADDRESSTYPEID` INT NOT NULL ,
  `ADDRESSTYPENAME` VARCHAR(45) NULL ,
  PRIMARY KEY (`ADDRESSTYPEID`) );

DROP TABLE `category`;
CREATE TABLE `category` (
  `CATEGORYID` int(11) NOT NULL AUTO_INCREMENT,
  `CATEGORYNAME` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`CATEGORYID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$

DROP TABLE `product`;
CREATE TABLE `product` (
  `PRODUCTID` int(11) NOT NULL AUTO_INCREMENT,
  `PROD_SHORT_NAME` varchar(45) DEFAULT NULL,
  `PRODUCTNAME` varchar(45) DEFAULT NULL,
  `PRODUCT_PRICE` float(8,2) DEFAULT NULL,
  `PRODUCT_IMAGE_PATH` varchar(100) DEFAULT NULL,
  `CATEGORYID` int(11) DEFAULT NULL,
  PRIMARY KEY (`PRODUCTID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$

INSERT INTO `AddressTypes` (`AddressTypeId`,`AddressTypeName`) VALUES (1,'Shipping');
INSERT INTO `AddressTypes` (`AddressTypeId`,`AddressTypeName`) VALUES (2,'Mailing');
INSERT INTO `AddressTypes` (`AddressTypeId`,`AddressTypeName`) VALUES (3,'Billing');

INSERT INTO `test`.`OwnerTypes` (`OwnerTypeId`, `OwnerTypeName`) VALUES ('1', 'Customer');
INSERT INTO `test`.`OwnerTypes` (`OwnerTypeId`, `OwnerTypeName`) VALUES ('2', 'Vendor');
